# **Data Integration and Encoding**

**importing pandas, numpy**

In [1]:
import pandas as pd
import numpy as np

**mounting drive to fetch data from google drive**

In [6]:
from google.colab import drive
drive.mount("/content/Drive")

Mounted at /content/Drive

**fetching data from dataframe**

In [8]:
titanic_df = pd.read_csv("/content/Drive/MyDrive/dsml/titanic.csv")
titanic_df.sample(5)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
594,0,2,male,37.0,1,0,26.00,S,Second,man,True,NaN,Southampton,no,False
339,0,1,male,45.0,0,0,35.50,S,First,man,True,NaN,Southampton,no,True
647,1,1,male,56.0,0,0,35.50,C,First,man,True,A,Cherbourg,yes,True
694,0,1,male,60.0,0,0,26.55,S,First,man,True,NaN,Southampton,no,True
743,0,3,male,24.0,1,0,16.10,S,Third,man,True,NaN,Southampton,no,False

**Concatenation**

In [9]:
df1 = pd.DataFrame({
    "acc" : [1,2,3],
    "name" : ["Saurav","Gaurav","Sandesh"],
    "age" : [24,23,19]
})

df2 = pd.DataFrame({
    "acc" : [4,5],
    "name" : ["Gyanu","Daya"],
    "age" : [43,50]
})

In [17]:
row_df = pd.concat([df1,df2])
row_df = row_df.set_index("acc")
row_df

        name  age
acc
1     Saurav   24
2     Gaurav   23
3    Sandesh   19
4      Gyanu   43
5       Daya   50

In [18]:
df3 = pd.DataFrame({
    "school" : ["JMC","KMC","Saraswati"]
})

In [19]:
column_df = pd.concat([df1,df3], axis = 1)
column_df

   acc     name  age     school
0    1   Saurav   24        JMC
1    2   Gaurav   23        KMC
2    3  Sandesh   19  Saraswati

**Merge**

In [20]:
new_df1 = pd.DataFrame({
    "key" : ["E","B","C","Z"],
    "inv_values" : [99,55,33,22],
    "account" : [1,2,5,7]
})

In [21]:
new_df2 = pd.DataFrame({
    "key" : ["A","B","C","D"],
    "hel_ration" : [66,0.67,67,20],
    "account" : [11,32,53,74]
})

In [26]:
merged_df = pd.merge(new_df1,new_df2,how="inner",on="key",suffixes=("df1","df2"))
merged_df

  key  inv_values  accountdf1  hel_ration  accountdf2
0   B          55           2        0.67          32
1   C          33           5       67.00          53

**Class task: doing all types of joins**

In [27]:
outer_merged_df = pd.merge(new_df1,new_df2,how="outer",on="key",suffixes=("df1","df2"))
outer_merged_df

  key  inv_values  accountdf1  hel_ration  accountdf2
0   A         NaN         NaN       66.00        11.0
1   B        55.0         2.0        0.67        32.0
2   C        33.0         5.0       67.00        53.0
3   D         NaN         NaN       20.00        74.0
4   E        99.0         1.0         NaN         NaN
5   Z        22.0         7.0         NaN         NaN

In [28]:
right_merged_df = pd.merge(new_df1,new_df2,how="right",on="key",suffixes=("df1","df2"))
right_merged_df

  key  inv_values  accountdf1  hel_ration  accountdf2
0   A         NaN         NaN       66.00          11
1   B        55.0         2.0        0.67          32
2   C        33.0         5.0       67.00          53
3   D         NaN         NaN       20.00          74

In [29]:
left_merged_df = pd.merge(new_df1,new_df2,how="left",on="key",suffixes=("df1","df2"))
left_merged_df

  key  inv_values  accountdf1  hel_ration  accountdf2
0   E          99           1         NaN         NaN
1   B          55           2        0.67        32.0
2   C          33           5       67.00        53.0
3   Z          22           7         NaN         NaN

In [32]:
cross_merged_df = pd.merge(new_df1,new_df2,how="cross")
cross_merged_df

   key_x  inv_values  account_x key_y  hel_ration  account_y
0      E          99          1     A       66.00         11
1      E          99          1     B        0.67         32
2      E          99          1     C       67.00         53
3      E          99          1     D       20.00         74
4      B          55          2     A       66.00         11
5      B          55          2     B        0.67         32
6      B          55          2     C       67.00         53
7      B          55          2     D       20.00         74
8      C          33          5     A       66.00         11
9      C          33          5     B        0.67         32
10     C          33          5     C       67.00         53
11     C          33          5     D       20.00         74
12     Z          22          7     A       66.00         11
13     Z          22          7     B        0.67         32
14     Z          22          7     C       67.00         53
15     Z          22          7     D       20.00         74

**join**

In [35]:
new_df1.join(new_df2,how="inner",lsuffix="_x")

  key_x  inv_values  account_x key  hel_ration  account
0     E          99          1   A       66.00       11
1     B          55          2   B        0.67       32
2     C          33          5   C       67.00       53
3     Z          22          7   D       20.00       74

In [37]:
new_df2.join(new_df1,how = "right",lsuffix = "_x")

  key_x  hel_ration  account_x key  inv_values  account
0     A       66.00         11   E          99        1
1     B        0.67         32   B          55        2
2     C       67.00         53   C          33        5
3     D       20.00         74   Z          22        7

**Stacking**

In [41]:
new_df1 = pd.DataFrame({
    "key" : ["E","B","C","Z"],
    "inv_values" : [99,55,33,22],
    "account" : [1,2,5,7]
}, index = ["W","X","Y","Z"]
)

new_df1

  key  inv_values  account
W   E          99        1
X   B          55        2
Y   C          33        5
Z   Z          22        7

In [43]:
stacked = new_df1.stack()
stacked

W  key            E
   inv_values    99
   account        1
X  key            B
   inv_values    55
   account        2
Y  key            C
   inv_values    33
   account        5
Z  key            Z
   inv_values    22
   account        7
dtype: object

In [44]:
unstacked = stacked.unstack()
unstacked

  key inv_values account
W   E         99       1
X   B         55       2
Y   C         33       5
Z   Z         22       7

**One Hot Encoding**

In [49]:
pd.get_dummies(titanic_df,columns = ["sex","embarked","embark_town"],dtype = int).sample(5)

,survived,pclass,age,sibsp,parch,fare,class,who,adult_male,deck,alive,alone,sex_female,sex_male,embarked_C,embarked_Q,embarked_S,embark_town_Cherbourg,embark_town_Queenstown,embark_town_Southampton
122,0,2,32.5,1,0,30.0708,Second,man,True,NaN,no,False,0,1,1,0,0,1,0,0
664,1,3,20.0,1,0,7.9250,Third,man,True,NaN,yes,False,0,1,0,0,1,0,0,1
109,1,3,NaN,1,0,24.1500,Third,woman,False,NaN,yes,False,1,0,0,1,0,0,1,0
25,1,3,38.0,1,5,31.3875,Third,woman,False,NaN,yes,False,1,0,0,0,1,0,0,1
568,0,3,NaN,0,0,7.2292,Third,man,True,NaN,no,True,0,1,1,0,0,1,0,0

**Label Encoder**

In [50]:
from sklearn.preprocessing import LabelEncoder

In [52]:
le = LabelEncoder()
encoded = le.fit_transform(titanic_df["embarked"])
encoded

array([2, 0, 2, 2, 2, 1, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 1, 2, 2, 0, 2, 2,
       1, 2, 2, 2, 0, 2, 1, 2, 0, 0, 1, 2, 0, 2, 0, 2, 2, 0, 2, 2, 0, 0,
       1, 2, 1, 1, 0, 2, 2, 2, 0, 2, 0, 2, 2, 0, 2, 2, 0, 3, 2, 2, 0, 0,
       2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1,
       2, 0, 2, 2, 0, 2, 1, 2, 0, 2, 2, 2, 0, 2, 2, 0, 1, 2, 0, 2, 0, 2,
       2, 2, 2, 0, 2, 2, 2, 0, 0, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 0, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 0, 2,
       2, 0, 2, 2, 2, 0, 2, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 2, 0, 0, 1, 2,
       1, 2, 2, 2, 2, 0, 2, 2, 2, 0, 1, 0, 2, 2, 2, 2, 1, 0, 2, 2, 0, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 1,
       2, 2, 0, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 0, 2, 1, 2, 2, 2,
       1, 2, 2, 2, 2, 2, 2, 2, 2, 0, 1, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 0,
       2, 2, 2, 1, 2, 0, 0, 2, 2, 0, 0, 2, 2, 0, 1, 1, 2, 1, 2, 2, 0, 0,
       0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 1, 2, 2, 0, 2, 2, 2, 0,
       1, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       0, 2, 0, 2, 2, 2, 1, 1, 2, 0, 0, 2, 1, 2, 0, 0, 1, 0, 0, 2, 2, 0,
       2, 0, 2, 0, 0, 2, 0, 0, 2, 2, 2, 2, 2, 2, 1, 0, 2, 2, 2, 0, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2,
       2, 2, 0, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 0, 0, 2, 0, 2, 2, 2, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 1, 0, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       0, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 0, 0, 2, 2, 2, 2, 1, 1, 2, 2, 0,
       2, 2, 2, 2, 1, 2, 2, 0, 2, 2, 2, 1, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2,
       2, 2, 2, 0, 0, 0, 2, 2, 2, 0, 2, 0, 2, 2, 2, 2, 0, 2, 2, 0, 2, 2,
       0, 2, 1, 0, 2, 2, 0, 0, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2,
       2, 1, 2, 2, 2, 2, 0, 2, 2, 0, 2, 0, 0, 2, 2, 0, 2, 2, 2, 0, 2, 1,
       2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 1, 1, 2, 2,
       2, 2, 2, 2, 0, 2, 0, 2, 2, 2, 1, 2, 2, 1, 2, 2, 0, 2, 2, 2, 2, 2,
       2, 2, 2, 0, 2, 2, 0, 0, 2, 0, 2, 2, 2, 2, 2, 1, 1, 2, 2, 1, 2, 0,
       2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 1, 0,
       2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 0, 2, 2, 2, 1, 0, 2, 0, 2, 0, 1,
       2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 0, 2, 1, 2, 2, 2, 2, 2, 2, 2,
       2, 1, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2,
       2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 0, 1, 1, 2,
       2, 2, 2, 0, 2, 2, 1, 2, 1, 2, 0, 2, 2, 2, 2, 2, 2, 1, 2, 0, 1, 2,
       2, 0, 2, 2, 2, 2, 0, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 1, 2, 0, 1, 3, 0, 2, 0, 2, 2, 0,
       2, 2, 2, 0, 2, 2, 0, 0, 2, 2, 2, 0, 2, 0, 2, 2, 0, 2, 2, 2, 2, 2,
       0, 0, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 0,
       2, 2, 2, 2, 2, 1, 2, 2, 2, 0, 1])

In [55]:
encoded.size

891

In [60]:
le.classes_

array(['C', 'Q', 'S', nan], dtype=object)

In [61]:
le.inverse_transform([0,1,3,2])

array(['C', 'Q', nan, 'S'], dtype=object)

**Label encoding male and female**

In [62]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

In [63]:
encoded = le.fit_transform(titanic_df["sex"])
encoded

array([1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1])

In [64]:
encoded.size

891

In [65]:
le.classes_

array(['female', 'male'], dtype=object)

In [66]:
le.inverse_transform([0,1])

array(['female', 'male'], dtype=object)